- name: Add a Application user
  ansible.builtin.user:
    name: roboshop
  register: APPUSER

#- name: Download & Extract {{COMPONENT}} Content
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
#    dest: /tmp
#    remote_src: yes

- name: Clean old {{COMPONENT}} Content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Create {{COMPONENT}} Content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: directory
  become_user: roboshop

- name: Download & Extract {{COMPONENT}} Content
  ansible.builtin.unarchive:
    src: http://172.31.12.154:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
  become_user: roboshop

