- name: Setup Prometheus Node Exporter
  import_role:
    name: prometheus
    tasks_from: nodeexporter.yml

- name: Setup Filebeat
  import_role:
    name: elk
    tasks_from: filebeat.yml

- name: Setup SystemD Config File
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
  notify: Reload

- name: Flush handlers
  meta: flush_handlers

- name: Start {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes

